<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>INDEX PAGE</title>
</head>
<body>
    <FORM>
        <table aria-colspan="2">
        <h3>IF YOU HAVE AN ID- JUST :: <a href="LOGIN.PHP">LOG IN</a></h3>
        <h3>IF YOU ARE NEW USER- JUST :: <a href="SIGNUP.PHP">SIGN UP</a></h3>
        </table>
    </FORM>
</body>
</html>